#!/bin/sh

configure_nvim() {
  git clone git@github.com:arewerage/astronvim.git ~/.config/nvim/lua/user
}

configure_user_dirs() {
  mv ~/Рабочий\ стол ~/desktop
  mv ~/Загрузки ~/download
  mv ~/Шаблоны ~/templates
  mv ~/Общедоступные ~/public
  mv ~/Документы ~/documents
  mv ~/Музыка ~/music
  mv ~/Изображения ~/pictures
  mv ~/Видео ~/videos
}

configure_nvim
configure_user_dirs
