#!/bin/sh
# shellcheck disable=2164

user_dirs() {
	mv ~/Рабочий\ стол ~/desktop
	mv ~/Загрузки ~/download
	mv ~/Шаблоны ~/templates
	mv ~/Общедоступные ~/public
	mv ~/Документы ~/documents
	mv ~/Музыка ~/music
	mv ~/Изображения ~/pictures
	mv ~/Видео ~/videos
}

journal_and_swap() {
	sudo journalctl --vacuum-size=500M && sudo journalctl --vacuum-time=7d
	sudo systemctl enable fstrim.timer
	sudo systemctl start fstrim.timer
	sudo systemctl status fstrim.timer
	sudo sysctl -w vm.swappiness=10
}

cleanup() {
	yay -Rsn firefox
	yay -Rsn nano nano-syntax-highlighting
	yay -Rsn zsh manjaro-zsh-config zsh-autosuggestions zsh-completions zsh-history-substring-search zsh-syntax-highlighting zsh-theme-powerlevel10k
	yay -Rsn gedit
	rm -rf ~/.cache/p10k-* ~/.mozilla .z* ~/.nanorc
}

wallpaper() {
	wget 'https://raw.githubusercontent.com/FrenzyExists/wallpapers/main/Gruv/houses.jpg' -O ~/.config/houses.jpg
	gsettings set org.gnome.desktop.background picture-uri-dark 'file:///home/awr/.config/houses.jpg'
}

themes() {
	yay -S gtk-engine-murrine sassc tela-icon-theme
	gsettings set org.gnome.desktop.interface icon-theme "'Tela-red-dark'"
}

gnome_settings() {
	gsettings set org.gnome.desktop.interface clock-show-seconds "true"
	gsettings set org.gnome.desktop.interface show-battery-percentage "true"
	gsettings set org.gnome.desktop.session idle-delay 900
	gsettings set org.gnome.desktop.peripherals.mouse accel-profile "'flat'"
	gsettings set org.gnome.desktop.peripherals.touchpad edge-scrolling-enabled "true"
	gsettings set org.gnome.desktop.peripherals.touchpad two-finger-scrolling-enabled "false"
	gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll "false"
	gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('xkb', 'ru')]"
	gsettings set org.gnome.desktop.input-sources xkb-options "['grp:caps_toggle']"
	gsettings set org.gnome.desktop.sound allow-volume-above-100-percent "true"
	gsettings set org.gtk.Settings.FileChooser show-hidden "true"
}

rustlang() {
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
}

apps() {
	yay -S google-chrome firefox alacritty discord timeshift qbittorrent telegram-desktop krita
	yay -S gimp blender obs-studio dconf-editor xp-pen-tablet
	sudo rm -rf /etc/xdg/autostart/xppentablet.desktop
}

console_utils() {
	yay -S starship fzf bat git-delta neofetch tldr zoxide yazi nodejs python silicon ranger
	yay -S exa tokei just mhwd-tui fish lld xclip npm ripgrep lazygit gdu bottom tree-sitter-cli
	yay -S ffmpegthumbnailer unarchiver jq poppler fd aseprite yarn

	cargo install rust-script cargo-modules
}

nvidia() {
	sudo mhwd -a pci nonfree 0300
}

neovim() {
	rm -rf ~/.config/nvim
	rm -rf ~/.local/share/nvim
	rm -rf ~/.local/state/nvim
	rm -rf ~/.cache/nvim

	rustup component add rust-analyzer

	git clone git@github.com:arewerage/astronvim_config_v4.git ~/.config/nvim
	yadm remote set-url origin git@github.com:arewerage/dotfiles.git
	nvim --headless +q
}

fish_shell() {
	chsh -s /bin/fish
}

user_dirs
journal_and_swap
cleanup
wallpaper
themes
gnome_settings
rustlang
apps
console_utils
nvidia
neovim
fish_shell

reboot
