import = ["/home/awr/.config/alacritty/themes/gruvbox.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 1

[window.dimensions]
columns = 100
lines = 25

[window.padding]
x = 10
y = 10
